import { chromium } from 'file:///D:/Users/User/AppData/Local/npm-cache/_npx/361ceb562f3b3235/node_modules/playwright/index.mjs';
const OUT = 'D:/UserProjects/AI/drive-coding/dev/.worktrees/slice-image-paste/.tmp/verify-c6';
const BASE = 'http://localhost:4005';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
const errors = [];
page.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
page.on('pageerror', e => errors.push('PAGEERROR: '+e.message));
await page.goto(BASE, { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: OUT+'/01-landing.png', fullPage: true });
console.log('URL:', page.url());
const btns = await page.$$eval('button', els => els.slice(0,40).map(e=>({t:e.textContent.trim().slice(0,40), aria:e.getAttribute('aria-label')})));
console.log('BUTTONS:', JSON.stringify(btns, null, 1));
const inputs = await page.$$eval('input,textarea', els => els.map(e=>({type:e.type, ph:e.placeholder})));
console.log('INPUTS:', JSON.stringify(inputs));
const bodyText = await page.$eval('body', e=>e.innerText.slice(0,600));
console.log('BODYTEXT:', bodyText);
console.log('CONSOLE ERRORS:', JSON.stringify(errors, null, 1));
await browser.close();
