import { chromium } from 'file:///D:/Users/User/AppData/Local/npm-cache/_npx/361ceb562f3b3235/node_modules/playwright/index.mjs';
const OUT = 'D:/UserProjects/AI/drive-coding/dev/.worktrees/slice-image-paste/.tmp/verify-c6';
const log = (...a) => console.log('[p6]', ...a);
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await page.goto('http://localhost:4005/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
await page.getByRole('button').filter({ hasText: /^claude\s+dev\b/ }).first().click();
await page.waitForURL('**/chat', { timeout: 90000 });
await page.waitForTimeout(3000);
log('at chat, clicking new session...');
await page.getByRole('button', { name: /סשן חדש/ }).click();
await page.waitForTimeout(4000);
await page.screenshot({ path: OUT+'/probe-newsession.png', fullPage: true });
// dump footer buttons + textarea visibility
const taVis = await page.locator('textarea').first().isVisible().catch(()=>false);
log('textarea visible:', taVis);
const btns = await page.$$eval('button', els => els.map(e=>e.getAttribute('aria-label')||e.textContent.trim().slice(0,20)).filter(Boolean));
log('BTNS:', JSON.stringify(btns.slice(-20)));
await browser.close();
