import { describe, expect, test } from "vitest"
import { ErrorScope } from "./error-scope.svelte"

describe("ErrorScope", () => {
  test("turn identity preserves an external message and a dismissed banner", () => {
    const errors = new ErrorScope()
    const first = { message: "same", at: 10 }
    errors.syncTurnError(first)
    expect(errors.message).toBe("prompt failed: same")
    errors.setExternal("prompt failed: same")
    errors.syncTurnError(first)
    expect(errors.message).toBe("prompt failed: same")
    errors.syncTurnError(null)
    expect(errors.message).toBe("prompt failed: same")
    errors.syncTurnError(first)
    errors.dismiss()
    errors.syncTurnError(first)
    expect(errors.message).toBeNull()
    errors.syncTurnError({ message: "same", at: 11 })
    expect(errors.message).toBe("prompt failed: same")
    errors.syncTurnError(null)
    expect(errors.message).toBeNull()
  })

  test("clearTransient follows origin and terminal policy", () => {
    const errors = new ErrorScope()
    errors.clearTransient()
    expect(errors.message).toBeNull()
    errors.setTransient("temporary")
    errors.clearTransient()
    expect(errors.message).toBeNull()
    errors.setExternal("external")
    errors.clearTransient()
    expect(errors.message).toBeNull()
    errors.syncTurnError({ message: "turn", at: 1 })
    errors.clearTransient()
    expect(errors.message).toBe("prompt failed: turn")
    errors.setTerminal("terminal")
    errors.clearTransient()
    expect(errors.message).toBe("terminal")
    errors.setExternal("external")
    errors.clearTransient()
    expect(errors.message).toBe("external")
    errors.dismiss()
    errors.clearTransient()
    expect(errors.message).toBeNull()
    expect(errors.terminal).toBe(true)
    errors.reset()
    expect(errors.terminal).toBe(false)
  })
})
