// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.
// This stub is committed so TypeScript can type-check docs-source.ts in dev.
// The build script overwrites this file with real doc content before bun --compile.

export const AGENT_DOCS: Record<string, string> = {}
