// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.
// This stub is committed so TypeScript can type-check server.ts in dev.
// The build script overwrites this file with real asset imports before bun --compile.

export const FE: Record<string, string> = {}
