// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.
// This stub is committed so TypeScript can type-check plugin-extract.ts in dev.
// The build script overwrites this file with the real plugin source before bun --compile.

export const PROMPT_INJECTOR_SRC = ""
