#!/usr/bin/env node

// packages/release/scripts/build-binary.mjs
// Builds a self-contained binary via bun build --compile.
//   1. Build the frontend (pnpm --filter @drive-coding/frontend build)
//   2. Codegen fe-manifest.gen.ts  ← Glob(frontend-dist/**/*):
//        import f0 from "<rel>" with { type:"file" }  ...
//        export const FE: Record<string,string> = { "/…": f0, … }
//   3. bun build --compile --define __IS_BINARY__=true \
//        --asset-naming="[dir]/[name].[ext]" <bin> --outfile dist/drive-coding[.exe]
//
// Run via: node packages/release/scripts/build-binary.mjs

import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// scripts/ is inside packages/release/scripts — go up twice to reach monorepo root
const releaseDir = path.resolve(__dirname, "..")
const repoRoot = path.resolve(__dirname, "../../..")

const frontendBuild = path.join(repoRoot, "packages", "frontend", "build")
const backendSrc = path.join(repoRoot, "packages", "backend", "src")
const backendBinEntry = path.join(backendSrc, "bin", "drive-coding.ts")
const feManifestPath = path.join(backendSrc, "fe-manifest.gen.ts")
const pluginSrcPath = path.join(repoRoot, "packages", "backend", "plugins", "prompt-injector.ts")
const pluginSrcGenPath = path.join(backendSrc, "plugin-src.gen.ts")

const releaseDist = path.join(releaseDir, "dist")
const isWindows = process.platform === "win32"
const binaryName = isWindows ? "drive-coding.exe" : "drive-coding"
const releaseBinOut = path.join(releaseDist, binaryName)

// Resolve the bun executable: explicit override → search PATH → default install dir.
// Don't hardcode ~/.bun/bin — bun may live elsewhere (e.g. D:\ProgramsAndApps\Bun\bin).
function resolveBun() {
  if (process.env.BUN_BIN) return process.env.BUN_BIN
  const exe = isWindows ? "bun.exe" : "bun"
  for (const dir of (process.env.PATH ?? "").split(path.delimiter)) {
    if (!dir) continue
    const candidate = path.join(dir, exe)
    if (existsSync(candidate)) return candidate
  }
  const home = process.env.USERPROFILE ?? process.env.HOME ?? ""
  const fallback = path.join(home, ".bun", "bin", exe)
  if (existsSync(fallback)) return fallback
  throw new Error("[build-binary] bun executable not found. Set BUN_BIN or add bun to PATH.")
}
const bunBin = resolveBun()

// Step 1: Build frontend
console.log("[build-binary] Step 1: building frontend…")
execFileSync("bun", ["run", "--filter", "@drive-coding/frontend", "build"], {
  cwd: repoRoot,
  stdio: "inherit",
  shell: isWindows,
})

// Step 2: Codegen fe-manifest.gen.ts
console.log("[build-binary] Step 2: generating fe-manifest.gen.ts…")

if (!existsSync(frontendBuild)) {
  throw new Error(`[build-binary] Frontend build dir missing: ${frontendBuild}`)
}

function walkDir(dir, base) {
  const entries = readdirSync(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath, base))
    } else {
      files.push(fullPath)
    }
  }
  return files
}

const allFiles = walkDir(frontendBuild, frontendBuild)

// Generate import lines and FE map entries
const importLines = []
const mapEntries = []

for (let i = 0; i < allFiles.length; i++) {
  const absFile = allFiles[i]
  // URL path: strip frontendBuild prefix, normalise to forward slashes
  const urlPath = "/" + path.relative(frontendBuild, absFile).replace(/\\/g, "/")
  // Relative path from fe-manifest.gen.ts (in backend/src/) to the asset
  const relFromManifest = path.relative(backendSrc, absFile).replace(/\\/g, "/")
  importLines.push(`import f${i} from "./${relFromManifest}" with { type: "file" }`)
  // Trailing comma on every entry — valid TS/JS, and avoids off-by-one at the last entry.
  mapEntries.push(`  ${JSON.stringify(urlPath)}: f${i},`)
}

const manifestContent = [
  "// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.",
  "// Committed stub (empty) is replaced at build time with real asset imports.",
  "",
  ...importLines,
  "",
  "export const FE: Record<string, string> = {",
  ...mapEntries,
  "}",
  "",
].join("\n")

writeFileSync(feManifestPath, manifestContent, "utf8")
console.log(`[build-binary] Step 2: wrote fe-manifest.gen.ts (${allFiles.length} assets)`)

// Step 2b: Codegen plugin-src.gen.ts — inline the plugin source as a string constant.
// This avoids the $bunfs path issue with .ts assets above the entry dir (../ escapes bundle root).
// Same pattern as fe-manifest.gen.ts: stub committed, real content written before compile, restored after.
console.log("[build-binary] Step 2b: generating plugin-src.gen.ts…")
if (!existsSync(pluginSrcPath)) {
  throw new Error(`[build-binary] Plugin source missing: ${pluginSrcPath}`)
}
const pluginSrcContent = readFileSync(pluginSrcPath, "utf8")
const pluginSrcGenContent = [
  "// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.",
  "// Committed stub (empty string) is replaced at build time with real plugin source.",
  "",
  `export const PROMPT_INJECTOR_SRC = ${JSON.stringify(pluginSrcContent)}`,
  "",
].join("\n")
writeFileSync(pluginSrcGenPath, pluginSrcGenContent, "utf8")
console.log(`[build-binary] Step 2b: wrote plugin-src.gen.ts (${pluginSrcContent.length} chars)`)

// Step 3: bun build --compile
console.log("[build-binary] Step 3: bun build --compile…")
rmSync(releaseDist, { recursive: true, force: true })
mkdirSync(releaseDist, { recursive: true })

execFileSync(
  bunBin,
  [
    "build",
    "--compile",
    "--define",
    "__IS_BINARY__=true",
    "--asset-naming=[dir]/[name].[ext]",
    "--target=bun",
    backendBinEntry,
    "--outfile",
    releaseBinOut,
  ],
  { stdio: "inherit" },
)

// Guard: binary must exist
if (!existsSync(releaseBinOut)) {
  throw new Error(`[build-binary] FATAL: ${releaseBinOut} was not produced.`)
}

// Guard: no sourcemaps in dist/
const mapLeak = readdirSync(releaseDist).filter((f) => f.endsWith(".map"))
if (mapLeak.length > 0) {
  throw new Error(`[build-binary] FATAL: sourcemap(s) found in dist/: ${mapLeak.join(", ")}`)
}

// Step 4: Restore the committed stub so `pnpm typecheck` in dev continues to pass.
// The generated manifest is only needed during `bun build --compile`; the stub
// is what TypeScript sees in normal dev/CI (no runtime import path needed — the
// stub's `FE = {}` satisfies type-checking with the Record<string,string> annotation).
const STUB_CONTENT = [
  "// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.",
  "// This stub is committed so TypeScript can type-check server.ts in dev.",
  "// The build script overwrites this file with real asset imports before bun --compile.",
  "",
  "export const FE: Record<string, string> = {}",
  "",
].join("\n")
writeFileSync(feManifestPath, STUB_CONTENT, "utf8")
console.log("[build-binary] Step 4: restored fe-manifest.gen.ts stub (for dev typecheck)")

// Step 4b: Restore plugin-src.gen.ts stub (same reason — dev typecheck must pass with empty string).
const PLUGIN_SRC_STUB = [
  "// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.",
  "// This stub is committed so TypeScript can type-check plugin-extract.ts in dev.",
  "// The build script overwrites this file with the real plugin source before bun --compile.",
  "",
  'export const PROMPT_INJECTOR_SRC = ""',
  "",
].join("\n")
writeFileSync(pluginSrcGenPath, PLUGIN_SRC_STUB, "utf8")
console.log("[build-binary] Step 4b: restored plugin-src.gen.ts stub (for dev typecheck)")

console.log(`[build-binary] Done. Binary: ${releaseBinOut}`)
