#!/usr/bin/env node

// packages/release/scripts/build-binary.mjs
// Builds a self-contained binary via bun build --compile.
//   1. Build the frontend (pnpm --filter @drive-coding/frontend-v2 build)
//   2. Codegen fe-manifest.gen.ts  ← Glob(frontend-dist/**/*):
//        import f0 from "<rel>" with { type:"file" }  ...
//        export const FE: Record<string,string> = { "/…": f0, … }
//   3. bun build --compile --define __IS_BINARY__=true \
//        --asset-naming="[dir]/[name].[ext]" <bin> --outfile dist/drive-coding[.exe]
//
// Run via: node packages/release/scripts/build-binary.mjs

import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// scripts/ is inside packages/release/scripts — go up twice to reach monorepo root
const releaseDir = path.resolve(__dirname, "..")
const repoRoot = path.resolve(__dirname, "../../..")

const frontendBuild = path.join(repoRoot, "packages", "frontend", "build")
const backendSrc = path.join(repoRoot, "packages", "backend", "src")
const backendBinEntry = path.join(backendSrc, "bin", "drive-coding.ts")
const feManifestPath = path.join(backendSrc, "fe-manifest.gen.ts")

const releaseDist = path.join(releaseDir, "dist")
const isWindows = process.platform === "win32"
const binaryName = isWindows ? "drive-coding.exe" : "drive-coding"
const releaseBinOut = path.join(releaseDist, binaryName)

// Resolve bun from common locations if not in PATH
const bunBin =
  process.env.BUN_BIN ??
  (isWindows ? path.join(process.env.USERPROFILE ?? "", ".bun", "bin", "bun.exe") : "bun")

// Step 1: Build frontend
console.log("[build-binary] Step 1: building frontend…")
execFileSync("pnpm", ["--filter", "@drive-coding/frontend-v2", "build"], {
  cwd: repoRoot,
  stdio: "inherit",
  shell: isWindows,
})

// Step 2: Codegen fe-manifest.gen.ts
console.log("[build-binary] Step 2: generating fe-manifest.gen.ts…")

if (!existsSync(frontendBuild)) {
  throw new Error(`[build-binary] Frontend build dir missing: ${frontendBuild}`)
}

function walkDir(dir, base) {
  const entries = readdirSync(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath, base))
    } else {
      files.push(fullPath)
    }
  }
  return files
}

const allFiles = walkDir(frontendBuild, frontendBuild)

// Generate import lines and FE map entries
const importLines = []
const mapEntries = []

for (let i = 0; i < allFiles.length; i++) {
  const absFile = allFiles[i]
  // URL path: strip frontendBuild prefix, normalise to forward slashes
  const urlPath = "/" + path.relative(frontendBuild, absFile).replace(/\\/g, "/")
  // Relative path from fe-manifest.gen.ts (in backend/src/) to the asset
  const relFromManifest = path.relative(backendSrc, absFile).replace(/\\/g, "/")
  importLines.push(`import f${i} from "./${relFromManifest}" with { type: "file" }`)
  mapEntries.push(`  ${JSON.stringify(urlPath)}: f${i}`)
}

const manifestContent = [
  "// AUTO-GENERATED by packages/release/scripts/build-binary.mjs — DO NOT EDIT.",
  "// Committed stub (empty) is replaced at build time with real asset imports.",
  "",
  ...importLines,
  "",
  "export const FE: Record<string, string> = {",
  ...mapEntries,
  "}",
  "",
].join("\n")

writeFileSync(feManifestPath, manifestContent, "utf8")
console.log(`[build-binary] Step 2: wrote fe-manifest.gen.ts (${allFiles.length} assets)`)

// Step 3: bun build --compile
console.log("[build-binary] Step 3: bun build --compile…")
rmSync(releaseDist, { recursive: true, force: true })
mkdirSync(releaseDist, { recursive: true })

execFileSync(
  bunBin,
  [
    "build",
    "--compile",
    "--define",
    "__IS_BINARY__=true",
    "--asset-naming=[dir]/[name].[ext]",
    "--target=bun",
    backendBinEntry,
    "--outfile",
    releaseBinOut,
  ],
  { stdio: "inherit" },
)

// Guard: binary must exist
if (!existsSync(releaseBinOut)) {
  throw new Error(`[build-binary] FATAL: ${releaseBinOut} was not produced.`)
}

// Guard: no sourcemaps in dist/
const mapLeak = readdirSync(releaseDist).filter((f) => f.endsWith(".map"))
if (mapLeak.length > 0) {
  throw new Error(`[build-binary] FATAL: sourcemap(s) found in dist/: ${mapLeak.join(", ")}`)
}

console.log(`[build-binary] Done. Binary: ${releaseBinOut}`)
